Prog_hw_api_wpfclient/MyPublicLibrary.Web/Models/Author.cs
// <copyright file="Author.cs" company="Szabados Gergely R7L4MZ">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
namespace MyPublicLibrary.Web.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// // Form Model / MVC ViewModel.
    /// </summary>
    public class Author
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Author"/> class.
        /// </summary>
        public Author()
        {
            this.Birthdate = DateTime.Now;
        }

        /// <summary>
        /// Gets or sets the id of the author.
        /// </summary>
        [Display(Name = "Author id")]
        [Required]
        public short AuthorId { get; set; }

        /// <summary>
        /// Gets or sets the name of the author.
        /// </summary>
        [Display(Name = "Author name")]
        [Required]
        [StringLength(40, MinimumLength = 5)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the birthdate of the author.
        /// </summary>
        [Display(Name = "Author birthdate")]
        [Required]
        public DateTime Birthdate { get; set; }

        /// <summary>
        /// Gets or sets the email of the author.
        /// </summary>
        [Display(Name = "Author email - must contain @")]
        [Required]
        [StringLength(60, MinimumLength = 10)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets the phonenumber of the author.
        /// </summary>
        [Display(Name = "Author phone")]
        [StringLength(11)]
        public string Phone { get; set; }

        /// <summary>
        /// Gets or sets the birthplace of the author.
        /// </summary>
        [Display(Name = "Author birthplace")]
        [StringLength(30)]
        public string Birthplace { get; set; }
    }
}

Prog_hw_api_wpfclient/MyPublicLibrary.Web/Models/AuthorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyPublicLibrary.Web.Models
{
    /// <summary>
    /// AuthorViewModel class.
    /// </summary>
    public class AuthorViewModel
    {
        /// <summary>
        /// Gets or sets the edited author.
        /// </summary>
        public Author EditedAuthor { get; set; }

        /// <summary>
        /// Gets or sets the list of the authors.
        /// </summary>
        public List<Author> ListOfAuthors { get; set; }
    }
}

Prog_hw_api_wpfclient/MyPublicLibrary.Web/Controllers/AuthorsController.cs
// <copyright file="AuthorsController.cs" company="Szabados Gergely R7L4MZ">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
namespace MyPublicLibrary.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using AutoMapper;
    using Microsoft.AspNetCore.Mvc;
    using MyPublicLibrary.Logic;
    using MyPublicLibrary.Web.Models;

    /// <summary>
    /// AuthorsController.
    /// </summary>
    public class AuthorsController : Controller
    {
        private IAuthorLogic logic;
        private IMapper mapper;
        private AuthorViewModel model;

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorsController"/> class.
        /// </summary>
        /// <param name="logic">IAuthorLogic.</param>
        /// <param name="mapper">IMapper.</param>
        public AuthorsController(IAuthorLogic logic, IMapper mapper)
        {
            this.logic = logic;
            this.mapper = mapper;

            this.model = new AuthorViewModel();
            this.model.EditedAuthor = new Models.Author();

            var authors = logic.GetAll().ToList();
            this.model.ListOfAuthors = mapper.Map<IList<Data.Author>, List<Models.Author>>(authors);
        }

        /// <summary>
        /// Index.
        /// </summary>
        /// <returns>A new view.</returns>
        // GET: Authors
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("AuthorsIndex", this.model);
        }

        /// <summary>
        /// Details view.
        /// </summary>
        /// <param name="id">Id of the author record.</param>
        /// <returns>AuthoreDetails.cshtml view.</returns>
        // GET: Authors/Details/5
        public ActionResult Details(int id)
        {
            return this.View("AuthorsDetails", this.GetAuthor(id));
        }

        /// <summary>
        /// Remove a record.
        /// </summary>
        /// <param name="id">Id of the author record.</param>
        /// <returns>Succesfull or not Failed.</returns>
        public ActionResult Remove(int id)
        {
            this.TempData["editResult"] = "Delete FAIL - Hivatkozik rá egy másik tábla";
            if (this.logic.Delete((short)id))
            {
                this.TempData["editResult"] = "Delete OK";
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        /// <summary>
        /// Edit an author.
        /// </summary>
        /// <param name="id">Id of the author record.</param>
        /// <returns>Authorsindex.cshtml view.</returns>
        // GET Authors/Edit/20
        public ActionResult Edit(int id)
        {
            this.ViewData["editAction"] = "Edit";
            this.model.EditedAuthor = this.GetAuthor(id);
            return this.View("AuthorsIndex", this.model);
        }

        /// <summary>
        /// Edit an author.
        /// </summary>
        /// <param name="author">Web.Model.Author (Formmodel).</param>
        /// <param name="editAction">An action.</param>
        /// <returns>An editresult: ok or failed.</returns>
        // POST Crud/Edit + send 1 author
        [HttpPost]
        public ActionResult Edit(Models.Author author, string editAction)
        {
            if (this.ModelState.IsValid && author != null)
            {
                this.TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    if (author.Email.Contains("@"))
                    {
                        try
                        {
                            this.logic.Create(new Data.Author { Name = author.Name, Birthdate = author.Birthdate, Email = author.Email, Phone = author.Phone, Birthplace = author.Birthplace });
                        }
                        catch (ArgumentException ex)
                        {
                            this.TempData["editResult"] = "Insert FAIL: " + ex.Message;
                        }
                    }
                    else
                    {
                        this.TempData["editResult"] = "Edit FAIL - Email must contains @ !";
                    }
                }
                else
                {
                    if (!this.logic.ChangeAuthor(author.AuthorId, author.Name, author.Birthdate, author.Email, author.Phone, author.Birthplace))
                    {
                        this.TempData["editResult"] = "Edit FAIL";
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.ViewData["editAction"] = "Edit";
                this.model.EditedAuthor = author;
                return this.View("AuthorsIndex", this.model);
            }
        }

        private Models.Author GetAuthor(int id)
        {
            Data.Author oneauthor = this.logic.GetById((short)id);
            return this.mapper.Map<Data.Author, Models.Author>(oneauthor);
        }
    }
}

Prog_hw_api_wpfclient/MyPublicLibrary.Web/Views/Authors/AuthorsDetails.cshtml
@model MyPublicLibrary.Web.Models.Author

@{ 
    ViewData["Title"] = "AuthorsDetails";
}

<h2>Datasheet of one car</h2>

@Html.ActionLink("Back to the list", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.AuthorId)</td>
        <td>@Html.DisplayFor(m => m.AuthorId)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Html.DisplayFor(m => m.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Birthdate)</td>
        <td>@Html.DisplayFor(m => m.Birthdate)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Email)</td>
        <td>@Html.DisplayFor(m => m.Email)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Phone)</td>
        <td>@Html.DisplayFor(m => m.Phone)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Birthplace)</td>
        <td>@Html.DisplayFor(m => m.Birthplace)</td>
    </tr>
</table>

Prog_hw_api_wpfclient/MyPublicLibrary.Web/Views/Authors/AuthorsEdit.cshtml
@model MyPublicLibrary.Web.Models.Author

<h2>AuthorsEdit</h2>

@using (Html.BeginForm("Edit", "Authors"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.AuthorId)
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Birthdate)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Birthdate)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Email)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Email)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Phone)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Phone)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Birthplace)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Birthplace)</div>


    <input type="submit" value="SEND" />
}

Prog_hw_api_wpfclient/MyPublicLibrary.Web/Views/Authors/AuthorsIndex.cshtml
@model MyPublicLibrary.Web.Models.AuthorViewModel

@{
    ViewData["Title"] = "Crud Index";
}

<h2>Authors Index</h2>

<p style="color:red">
    @TempData["editResult"]
</p>

@await Html.PartialAsync("AuthorsEdit", Model.EditedAuthor)

@await Html.PartialAsync("AuthorsList", Model.ListOfAuthors)

Prog_hw_api_wpfclient/MyPublicLibrary.Web/Views/Authors/AuthorsList.cshtml
@model IEnumerable<MyPublicLibrary.Web.Models.Author>

<h2>AuthorList</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database!!!</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Name)</th>
            <th>@Html.DisplayNameFor(m => m.First().Birthdate)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.Name)</td>
                <td>@Html.DisplayFor(m => item.Birthdate)</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.AuthorId })</td>
                <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.AuthorId })</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.AuthorId })</td>
            </tr>
        }
    </table>
}